/**
 * Beat template library — the heart of the build (PRD §5).
 *
 * Every non-generate beat is a reusable component + JSON config, built once
 * and shared by every student. Authoring a lesson = filling JSON, not building
 * UI. This file is the typed contract those JSON configs must satisfy.
 *
 * Design-lock milestone (PRD §12.1) implements: drag_sort, select, lever.
 * The remaining types are declared here so lesson JSON can reference them and
 * the player can render "coming soon" placeholders until they're built.
 */

export type BeatType =
  | "drag_sort"
  | "drag_label"
  | "lever"
  | "select"
  | "type_answer"
  | "generate"
  | "watch"
  | "speak";

/** An authored visual that narrates the topic (AI-generated by David, dropped
 * in /public/media/). Beats render fine while the file doesn't exist yet —
 * the slot simply stays hidden until the image is added. */
export interface BeatImage {
  /** Public path, e.g. "/media/l1-ai-around-you.png". */
  src: string;
  alt: string;
  caption?: string;
}

interface BeatBase {
  id: string;
  type: BeatType;
  /** Short one-line setup shown above the interaction. */
  prompt: string;
  /** Optional visual narration shown between the prompt and the interaction. */
  image?: BeatImage;
}

/** drag_sort — drag items into labeled buckets. */
export interface DragSortBeat extends BeatBase {
  type: "drag_sort";
  items: { id: string; label: string }[];
  buckets: { id: string; label: string }[];
  /** itemId -> bucketId */
  correct: Record<string, string>;
}

/** select — tap 1-of-N (predict / quiz), reveal with why. */
export interface SelectBeat extends BeatBase {
  type: "select";
  question: string;
  options: { id: string; label: string; explain: string }[];
  correct: string;
}

/** lever — drag a slider, watch the outcome change live; find the target. */
export interface LeverBeat extends BeatBase {
  type: "lever";
  /** Ordered states, one per lever notch (index 0..n-1). A state's optional
   * image becomes the live preview — the visual literally changes as the
   * student pulls the lever (visual narration). */
  states: { label: string; description: string; image?: string }[];
  /** Index into states the student is asked to land on. */
  target: number;
  /** Label under the two ends of the track. */
  minLabel: string;
  maxLabel: string;
}

/** watch — short YouTube embed (2–3 min max), complement not spine. */
export interface WatchBeat extends BeatBase {
  type: "watch";
  videoId: string;
  /** Optional clip window, seconds. Keeps passive time ≤3 min (PRD §F2). */
  start?: number;
  end?: number;
  /** Attribution shown under the player, e.g. "CGP Grey — How Machines Learn". */
  source: string;
}

/** type_answer — short free answer, concept-checked (keyword rubric for now;
 * swapped for LLM concept-check when the tutor lands). Kind phrasing on miss;
 * after two misses we show a model answer and let the student continue —
 * never a red-X wall (PRD §F3). */
export interface TypeAnswerBeat extends BeatBase {
  type: "type_answer";
  question: string;
  /** Groups of synonyms; the answer must touch at least `minMatches` groups. */
  keywords: string[][];
  minMatches: number;
  hint: string;
  sampleAnswer: string;
}

export type Beat =
  | DragSortBeat
  | SelectBeat
  | LeverBeat
  | WatchBeat
  | TypeAnswerBeat;

export interface Lesson {
  id: string;
  track: string;
  day: number;
  title: string;
  /** Estimated minutes, shown on the home card. */
  minutes: number;
  beats: Beat[];
  /** One-line tease of tomorrow's lesson. */
  tomorrow?: string;
}
